name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Desactiva la clonación superficial para obtener el historial completo de Git

      - name: Ejecutar análisis de SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Tu token guardado en Secrets